PRAGMA auto_vacuum=OFF;
PRAGMA page_size=1024;
BEGIN;
CREATE TABLE abc AS SELECT 1 AS a, 2 AS b, 3 AS c;
CREATE TABLE def AS SELECT 1 AS d, 2 AS e, 3 AS f;
COMMIT;
CREATE TABLE hij(h, i, j);
INSERT INTO abc SELECT * FROM abc;
INSERT INTO abc SELECT * FROM abc;
INSERT INTO abc SELECT * FROM abc;
INSERT INTO abc SELECT * FROM abc;
INSERT INTO abc SELECT * FROM abc;
PRAGMA temp_store = memory;
BEGIN;
SELECT random() FROM abc LIMIT 1;
INSERT INTO abc SELECT randstr(10,10), 0, 0 FROM abc WHERE random()%2==0;
DELETE FROM abc WHERE random()%2!=0;
COMMIT;
BEGIN;
SELECT random() FROM abc LIMIT 1;
INSERT INTO abc SELECT randstr(10,10), 0, 0 FROM abc WHERE random()%2==0;
DELETE FROM abc WHERE random()%2!=0;
COMMIT;
