ATTACH 'test.db2' AS aux;
CREATE TABLE t1(a, b);
INSERT INTO t1 VALUES('a main', 'b main');
CREATE VIEW v1 AS SELECT * FROM t1;
CREATE VIEW v2 AS SELECT * FROM t1;
CREATE TEMP TABLE t1(a, b);
INSERT INTO temp.t1 VALUES('a temp', 'b temp');
CREATE VIEW temp.v1 AS SELECT * FROM t1;
CREATE TABLE aux.t1(a, b);
INSERT INTO aux.t1 VALUES('a aux', 'b aux');
CREATE VIEW aux.v1 AS SELECT * FROM t1;
CREATE VIEW aux.v2 AS SELECT * FROM t1;
CREATE VIEW aux.v3 AS SELECT * FROM t1;
CREATE VIEW "new view" AS SELECT * FROM t1 AS x, t1 AS y;
SELECT * FROM "new view";
SELECT * FROM sqlite_master WHERE name = 'new view';
DROP VIEW "new view";
SELECT * FROM sqlite_master WHERE name = 'new view';
SELECT * FROM "new view";
