SELECT json_patch('{;
SELECT json_patch('{;
SELECT json_patch('[1,2,3]','{"x":null}');
SELECT json_patch('[1,2,3]','{"x":null,"y":1,"z":null}');
SELECT json_patch('{}','{"a":{"bb":{"ccc":null}}}');
SELECT json_patch('{}','{"a":{"bb":{"ccc":[1,null,3]}}}');
SELECT json_patch('{}','{"a":{"bb":{"ccc":[1,{"dddd":null},3]}}}');
SELECT json_patch('{"a":"b"}','{"a":"c"}');
SELECT coalesce(json_patch(null,'{"a":"c"}'), 'real-null');
SELECT json_patch('{"a":"b"}','{"b":"c"}');
SELECT json_patch('{"a":"b"}','{"a":null}');
SELECT json_patch('{"a":"b","b":"c"}','{"a":null}');
SELECT json_patch('{"a":["b"]}','{"a":"c"}');
SELECT json_patch('{"a":"c"}','{"a":["b"]}');
SELECT json_patch('{"a":{"b":"c"}}','{"a":{"b":"d","c":null}}');
SELECT json_patch('{"a":[{"b":"c"}]}','{"a":[1]}');
SELECT json_patch('["a","b"]','["c","d"]');
SELECT json_patch('{"a":"b"}','["c"]');
SELECT json_patch('{"a":"foo"}','null');
SELECT coalesce(json_patch('{"a":"foo"}',null), 'real-null');
SELECT json_patch('{"a":"foo"}','"bar"');
SELECT json_patch('{"e":null}','{"a":1}');
SELECT json_patch('[1,2]','{"a":"b","c":null}');
SELECT json_patch('{}','{"a":{"bb":{"ccc":null}}}');
