CREATE TRIGGER tr1 AFTER UPDATE OF d ON t6 BEGIN
SELECT 1, 2, 3;
END;
SELECT * FROM t2 INDEXED BY i4 ORDER BY a;
DROP TRIGGER tr2;
DROP TABLE IF EXISTS t7; CREATE TABLE t7(c, d);
DROP INDEX IF EXISTS i5; CREATE INDEX i5 ON t7(c);
DROP TRIGGER IF EXISTS tr3;
CREATE TRIGGER tr3 AFTER INSERT ON t7 BEGIN SELECT 1, 2, 3 ; END;
CREATE TRIGGER tr4 AFTER UPDATE OF a ON t8 BEGIN
SELECT 1, 2, 3;
END;
