CREATE TABLE t1(x);
INSERT INTO t1 VALUES(123);
SELECT * FROM t1;
CREATE TABLE t2(y);
CREATE TABLE t3(z);
SELECT * FROM t1;
CREATE TEMP TRIGGER r1 AFTER INSERT ON t1 BEGIN
INSERT INTO t2 VALUES(new.rowid);
END;
SELECT * FROM t3;
SELECT name FROM sqlite_temp_master;
