CREATE TABLE x(x INTEGER PRIMARY KEY, y INT NOT NULL);
INSERT INTO x(y) VALUES(1);
INSERT INTO x(y) VALUES(1);
CREATE TEMP VIEW vx AS SELECT x, y, 0 AS yy FROM x;
CREATE TEMP TRIGGER tx INSTEAD OF UPDATE OF y ON vx
BEGIN
UPDATE x SET y = new.y WHERE x = new.x;
END;
SELECT * FROM vx;
UPDATE vx SET y = yy;
SELECT * FROM vx;
CREATE TRIGGER ty AFTER INSERT ON x BEGIN
SELECT wen.x; -- Unrecognized name
END;
INSERT INTO x VALUES(1,2);
CREATE TRIGGER tz AFTER UPDATE ON x BEGIN
SELECT dlo.x; -- Unrecognized name
END;
UPDATE x SET y=y+1;
CREATE TABLE t2(a INTEGER PRIMARY KEY, b);
INSERT INTO t2 VALUES(1,2);
CREATE TABLE changes(x,y);
CREATE TRIGGER r1t2 AFTER UPDATE ON t2 BEGIN
INSERT INTO changes VALUES(new.a, new.b);
END;
UPDATE t2 SET a=a+10;
SELECT * FROM changes;
CREATE TRIGGER r2t2 AFTER DELETE ON t2 BEGIN
INSERT INTO changes VALUES(old.a, old.c);
END;
DELETE FROM t2;
CREATE TABLE t3(;
CREATE TABLE t3_changes(colnum, oldval, newval);
INSERT INTO t3 VALUES(;
CREATE TRIGGER t3c1 AFTER UPDATE ON t3
WHEN old.c1!=new.c1 BEGIN
INSERT INTO t3_changes VALUES(1, old.c1, new.c1);
END;
SELECT * FROM t3_changes;
UPDATE t3 SET c1='b1';
SELECT * FROM t3_changes ORDER BY rowid DESC LIMIT 1;
SELECT count(*) FROM t3_changes;
SELECT * FROM t3_changes WHERE colnum=1;
