PRAGMA auto_vacuum = 0;
PRAGMA journal_mode = WAL;
CREATE TABLE t1(x, y);
INSERT INTO t1 VALUES('a', 'b');
INSERT INTO t1 VALUES('g', 'h');
PRAGMA wal_checkpoint;
PRAGMA wal_checkpoint;
INSERT INTO t1 VALUES('k', 'l');
INSERT INTO t1 VALUES(1, 2);
INSERT INTO t1 VALUES(3, 4);
INSERT INTO t1 VALUES(5, 6);
PRAGMA wal_checkpoint;
PRAGMA cache_size = 10;
BEGIN;
CREATE TABLE t2(x, y);
INSERT INTO t2 VALUES('abc', 'xyz');
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
PRAGMA auto_vacuum = 0;
PRAGMA journal_mode = WAL;
BEGIN;
CREATE TABLE t2(x, y);
INSERT INTO t2 VALUES('abc', 'xyz');
INSERT INTO t2 SELECT x||y, y||x FROM t2;
INSERT INTO t2 SELECT x||y, y||x FROM t2;
COMMIT;
